name: Installers

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  # Java version to use in the Jitsi Desktop jars
  INSTALLER_JAVA_VERSION: 17

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  version:
    name: Versioning
    runs-on: ubuntu-latest
    outputs:
      jitsi_version_major: ${{ steps.parse.outputs.jitsi_version_major }}
      jitsi_version_minor: ${{ steps.parse.outputs.jitsi_version_minor }}
      jitsi_version_suffix: ${{ steps.parse.outputs.jitsi_version_suffix }}
      jitsi_version_git: ${{ steps.parse.outputs.jitsi_version_git }}
      jitsi_version_ncommits: ${{ steps.parse.outputs.jitsi_version_ncommits }}
      jitsi_version_hash: ${{ steps.parse.outputs.jitsi_version_hash }}
      jitsi_version_short: ${{ steps.parse.outputs.jitsi_version_short }}
      jitsi_version_full: ${{ steps.parse.outputs.jitsi_version_full }}
      jitsi_version_deb: ${{ steps.parse.outputs.jitsi_version_deb }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.INSTALLER_JAVA_VERSION }}
          distribution: temurin

      # don't use the setup-java cache option as this only caches what is
      # necessary for the version, not the other jobs
      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-version-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-version-

      - name: Parse version
        id: parse
        run: resources/version.sh

  javah:
    name: Compile Java for native headers
    runs-on: ubuntu-latest
    needs:
      - version
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.INSTALLER_JAVA_VERSION }}
          distribution: temurin
          cache: maven

      - name: Compile
        run: mvn -B compile

      - name: Upload JNI headers
        uses: actions/upload-artifact@v3
        with:
          name: javah
          path: target/native

  wix:
    name: Windows ${{ matrix.arch.actions }}
    runs-on: windows-latest
    needs: version
    strategy:
      matrix:
        arch:
          #- { actions: x86, cmake: Win32, cmake_opposite_arch: x64, java: "x86" }
          - { actions: x64, cmake: x64, cmake_opposite_arch: Win32, java: "x86-64" }
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Java
        id: install_java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ env.INSTALLER_JAVA_VERSION }}
          architecture: ${{ matrix.arch.actions }}
          cache: maven

      - name: Build Java
        shell: cmd
        run: mvn -B -DskipTests -Drevision=${{ needs.version.outputs.jitsi_version_full }} package

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Verify Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Build natives
        env:
          JAVA_HOME: ${{ steps.install_java.outputs.path }}
        shell: cmd
        run: |
          cd %GITHUB_WORKSPACE%\native
          cmake -B cmake-build-${{ matrix.arch.actions }} -A ${{ matrix.arch.cmake }} ^
            -DMAIN_VERSION=${{ needs.version.outputs.jitsi_version_full }} ^
            -DGIT_VERSION=${{ needs.version.outputs.jitsi_version_git }}
          cmake --build cmake-build-${{ matrix.arch.actions }} --config Release --target install

      - name: Upload CMake logs on failure
        if: ${{ failure() }}
        run: Compress-Archive -Path $Env:GITHUB_WORKSPACE/native/windows/src/native/cmake-build-${{ matrix.arch.actions }} -DestinationPath $Env:GITHUB_WORKSPACE/debug-logs.zip

      - name: Upload Debug logs
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: win-${{ matrix.arch.actions }}-debug
          path: debug*

      - name: Set up Java
        id: install_java_x64
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.INSTALLER_JAVA_VERSION }}
          architecture: x64
          distribution: temurin

      - name: Build installer
        env:
          JAVA_HOME: ${{ steps.install_java_x64.outputs.path }}
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE/resources/install
          ./gradlew --no-daemon --stacktrace windowsZip signMsi -Papplication.target=${{ matrix.arch.java }} -Pversion=2.14.1.0 -PgitVersion=2.14.1.0

      - name: Upload msi
        uses: actions/upload-artifact@v3
        with:
          name: jitsi-win-${{ matrix.arch.actions }}
          path: |
            resources/install/build/install/wix/jitsi-*.msi
            resources/install/build/distributions/jitsi-*.zip


  release:
    #if: github.ref == 'refs/heads/master'
    needs:
      - version
      - wix
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download binaries
        uses: actions/download-artifact@v3
        with:
          path: target

      - name: Create release
        uses: ncipollo/release-action@a2e71bdd4e7dab70ca26a852f29600c98b33153e
        with:
          artifacts: "target/**/*.msi,target/**/jitsi-*-win-*.zip"
          allowUpdates: true
          prerelease: true
          draft: true
          tag: r${{ needs.version.outputs.jitsi_version_short }}
          omitBody: true
          removeArtifacts: true
          replacesArtifacts: true
          token: ${{ secrets.GITHUB_TOKEN }}
          artifactErrorsFailBuild: true

  #deploy:
  #  name: Deploy Debian packages
  #  if: github.ref == 'refs/heads/master'
  #  needs:
  #    - version
  #    - release
  #  uses: ./.github/workflows/deploy-debian.yml
  #  with:
  #    release_type: unstable
  #    tag: r${{ needs.version.outputs.jitsi_version_short }}
  #  secrets: inherit
